#!/bin/bash
# install-gateway.sh - Gateway 설치 (cloudflared + Traefik)
# Phase 5: Gateway 설치 - Chain Node 1 (진입점)

set -e

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

JSON_OUTPUT=false
TUNNEL_TOKEN=""
DOMAIN=""
NODE_NAME=""
NEXT_NODE_IP=""

# 인자 파싱
while [[ $# -gt 0 ]]; do
    case $1 in
        --json) JSON_OUTPUT=true; shift ;;
        --token) TUNNEL_TOKEN="$2"; shift 2 ;;
        --domain) DOMAIN="$2"; shift 2 ;;
        --name) NODE_NAME="$2"; shift 2 ;;
        --next) NEXT_NODE_IP="$2"; shift 2 ;;
        *) shift ;;
    esac
done

log() {
    [[ "$JSON_OUTPUT" == "false" ]] && echo -e "$1"
}

error() {
    if [[ "$JSON_OUTPUT" == "true" ]]; then
        echo "{\"success\":false,\"error\":\"$1\"}"
    else
        echo -e "${RED}[ERROR]${NC} $1" >&2
    fi
    exit 1
}

# Docker 확인
if ! command -v docker &>/dev/null; then
    error "Docker가 설치되어 있지 않습니다"
fi

if ! docker info &>/dev/null; then
    error "Docker 데몬이 실행 중이 아닙니다"
fi

# 필수 인자 확인 (JSON 모드에서만 강제)
if [[ "$JSON_OUTPUT" == "true" ]]; then
    if [[ -z "$TUNNEL_TOKEN" ]]; then
        error "Cloudflare Tunnel 토큰이 필요합니다 (--token)"
    fi
    if [[ -z "$DOMAIN" ]]; then
        error "도메인이 필요합니다 (--domain)"
    fi
    if [[ -z "$NODE_NAME" ]]; then
        error "노드 이름이 필요합니다 (--name)"
    fi
fi

# 대화형 모드
if [[ -z "$TUNNEL_TOKEN" ]]; then
    log ""
    log "${BLUE}[?]${NC} Cloudflare Tunnel 설정"
    log ""
    log "  Cloudflare Zero Trust Dashboard에서 Tunnel을 생성하고"
    log "  토큰을 복사해주세요."
    log ""
    log "  1. https://one.dash.cloudflare.com → Networks → Tunnels"
    log "  2. Create a tunnel → Cloudflared 선택"
    log "  3. 이름 입력 후 Save tunnel"
    log "  4. 토큰 복사 (eyJ... 형태)"
    log ""
    read -p "  Tunnel Token: " TUNNEL_TOKEN
fi

if [[ -z "$DOMAIN" ]]; then
    log ""
    read -p "  도메인 (예: codepoet.site): " DOMAIN
fi

if [[ -z "$NODE_NAME" ]]; then
    log ""
    read -p "  노드 이름 (예: nas, mac, linux): " NODE_NAME
fi

if [[ -z "$NEXT_NODE_IP" ]]; then
    log ""
    log "${BLUE}[?]${NC} Traefik Chain 다음 노드"
    log "  이 노드에서 처리 못하는 요청을 전달할 다음 노드의 IP를 입력하세요."
    log "  (마지막 노드이거나 싱글노드면 빈칸으로 두세요)"
    log ""
    read -p "  다음 노드 IP (없으면 Enter): " NEXT_NODE_IP
fi

log ""
log "${GREEN}[*]${NC} Gateway 설치 시작..."

# 1. gateway 네트워크 생성
log "  - gateway 네트워크 생성..."
docker network create gateway 2>/dev/null || true

# 2. 작업 디렉토리 생성
WORK_DIR="$HOME/.terrafy/gateway"
mkdir -p "$WORK_DIR"

# 3. cloudflared 컨테이너 확인/실행
if docker ps --format '{{.Names}}' | grep -q '^cloudflared$'; then
    log "  ${YELLOW}[!]${NC} cloudflared가 이미 실행 중 - 재설정합니다"
    docker rm -f cloudflared >/dev/null 2>&1 || true
fi

log "  - cloudflared 컨테이너 실행..."
docker run -d \
    --name cloudflared \
    --network gateway \
    --restart always \
    cloudflare/cloudflared:latest \
    tunnel --no-autoupdate run --token "$TUNNEL_TOKEN" >/dev/null

# 4. Traefik 설정 생성
log "  - Traefik 설정 생성..."

# Chain 라우팅 설정
if [[ -n "$NEXT_NODE_IP" ]]; then
    FALLBACK_ROUTER="
            # Chain Fallback → 다음 노드
            chain-fallback:
              rule: \"HostRegexp(\\\`.*\\\`)\"
              priority: 1
              entryPoints: [web]
              service: next-node"
    FALLBACK_SERVICE="
            next-node:
              loadBalancer:
                servers:
                  - url: \"http://${NEXT_NODE_IP}:80\""
else
    # 마지막 노드 - 404 반환
    FALLBACK_ROUTER=""
    FALLBACK_SERVICE=""
fi

# docker-compose.yml 생성
cat > "$WORK_DIR/docker-compose.yml" << EOF
# Gateway - cloudflared + Traefik (Chain Node 1)
# Generated by terrafy

services:
  init-config:
    image: busybox
    container_name: traefik-init
    command:
      - sh
      - -c
      - |
        # traefik.yml
        cat > /config/traefik.yml << 'TRAEFIK_STATIC'
        api:
          dashboard: true
          insecure: true
        entryPoints:
          web:
            address: ":80"
        providers:
          docker:
            endpoint: "unix:///var/run/docker.sock"
            exposedByDefault: false
            network: gateway
          file:
            directory: /etc/traefik/dynamic
            watch: true
        log:
          level: INFO
        TRAEFIK_STATIC

        # routes.yml
        mkdir -p /config/dynamic
        cat > /config/dynamic/routes.yml << 'TRAEFIK_ROUTES'
        http:
          routers:${FALLBACK_ROUTER}
            # 여기에 서비스 라우터 추가

          services:${FALLBACK_SERVICE}
            # 여기에 서비스 정의 추가
        TRAEFIK_ROUTES

        # welcome page
        mkdir -p /welcome
        cat > /welcome/index.html << 'WELCOME_HTML'
        <!DOCTYPE html>
        <html><head><title>homelab-${NODE_NAME} | ${DOMAIN}</title>
        <style>body{font-family:system-ui;min-height:100vh;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#1a1a2e,#16213e);color:#fff;margin:0}.container{text-align:center}h1{font-size:3rem;background:linear-gradient(90deg,#00d4ff,#7b2ff7);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.badge{display:inline-block;padding:0.5rem 1rem;background:#2d2d44;border-radius:8px;margin:1rem 0}p{color:#a0a0a0}</style></head>
        <body><div class="container"><h1>homelab-${NODE_NAME}</h1><div class="badge">Gateway</div><p>Traefik Chain Node 1 | ${DOMAIN}</p></div></body>
        </html>
        WELCOME_HTML

        chmod -R 644 /config/* /welcome/*
        chmod 755 /config /config/dynamic /welcome
        echo "Config files created"
    volumes:
      - traefik_config:/config
      - welcome_html:/welcome

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik:ro
    networks:
      - gateway
    depends_on:
      init-config:
        condition: service_completed_successfully

  welcome:
    image: nginx:alpine
    container_name: welcome
    restart: unless-stopped
    volumes:
      - welcome_html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.welcome.rule=Host(\`test.${DOMAIN}\`) || Host(\`homelab-${NODE_NAME}.${DOMAIN}\`)"
      - "traefik.http.routers.welcome.priority=10"
      - "traefik.http.routers.welcome.entrypoints=web"
    networks:
      - gateway
    depends_on:
      init-config:
        condition: service_completed_successfully

networks:
  gateway:
    name: gateway
    external: true

volumes:
  traefik_config:
  welcome_html:
EOF

# 5. Traefik 실행
log "  - Traefik 스택 실행..."
cd "$WORK_DIR"
docker compose up -d >/dev/null 2>&1

# 6. 확인
sleep 5

CLOUDFLARED_RUNNING=$(docker ps --format '{{.Names}}' | grep -q '^cloudflared$' && echo "true" || echo "false")
TRAEFIK_RUNNING=$(docker ps --format '{{.Names}}' | grep -q '^traefik$' && echo "true" || echo "false")

if [[ "$CLOUDFLARED_RUNNING" == "true" && "$TRAEFIK_RUNNING" == "true" ]]; then
    if [[ "$JSON_OUTPUT" == "true" ]]; then
        echo "{\"success\":true,\"status\":\"installed\",\"cloudflared\":true,\"traefik\":true,\"domain\":\"$DOMAIN\",\"node\":\"$NODE_NAME\"}"
    else
        log ""
        log "${GREEN}[✓]${NC} Gateway 설치 완료!"
        log ""
        log "  cloudflared: 실행 중"
        log "  Traefik:     실행 중"
        log ""
        log "  Dashboard:   http://localhost:8080"
        log "  Welcome:     https://homelab-${NODE_NAME}.${DOMAIN}"
        log "  Test:        https://test.${DOMAIN}"
        log ""
        log "${YELLOW}[!]${NC} Cloudflare Dashboard에서 Tunnel Public Hostname 설정:"
        log "  1. Networks → Tunnels → 생성한 터널 선택"
        log "  2. Public Hostname 탭 → Add a public hostname"
        log "  3. Subdomain: * / Domain: ${DOMAIN}"
        log "  4. Service: http://traefik:80"
    fi
else
    error "Gateway 설치 실패 (cloudflared: $CLOUDFLARED_RUNNING, traefik: $TRAEFIK_RUNNING)"
fi
